# Generated by Django 5.2.11 on 2026-02-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='business',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
